### ISSUE TITLE
HTML として出力するときにエスケープする

### ISSUE THREAD

**Issue by takano32** [sotokisehiro/chatux-server-llm#3]
HTML として表示したときに意図しないタグになってしまうことがある。

[![Image from Gyazo](https://i.gyazo.com/0319b0a876ad5eb120bb972e078ec925.png)](https://gyazo.com/0319b0a876ad5eb120bb972e078ec925)

**Comment by sotokisehiro** [comment]
問題、おおむね理解しました。対応策を検討しますのでお時間ください。よろしくお願いいたします。
