### ISSUE TITLE
[Docker] HTML をカスタマイズ可能にする

### ISSUE THREAD

**Issue by takano32** [sotokisehiro/chatux-server-llm#8]
`docker compose up` したときに HTML をカスタマイズ可能にするとよいというアドバイス

1. https://x.com/ZIKUU_space/status/1703359022072771042?s=20
2. https://x.com/sotokisehiro/status/1703503372983357502?s=20

特に大きな不都合は思いつかないので検討と対応をします。 / @takano32

**Comment by sotokisehiro** [comment]
よろしくお願いします！
（一瞬「このくらいなら自分で修正してもいいかな？」と考えたのですが、万一の事態を考慮して思い直しました）
